name: Setup Rust for Tauri
description: Setup Rust toolchain with caching configured for Tauri project

inputs:
  components:
    description: Additional Rust components to install (e.g., rustfmt, clippy)
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Configure sccache environment
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: ${{ inputs.components }}
        cache-workspaces: src-tauri -> src-tauri/target
