name: Build Sidecar Binaries
description: Build sidecar binaries for Tauri application

inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu). If not specified, uses host triple.'
    required: false
    default: ''
  profile:
    description: 'Build profile (debug or release)'
    required: false
    default: 'debug'

runs:
  using: composite
  steps:
    - name: Build sidecar (Unix)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: src-tauri
      run: |
        TARGET="${{ inputs.target }}"
        PROFILE="${{ inputs.profile }}"

        # Get host triple if target not specified
        if [ -z "$TARGET" ]; then
          TARGET=$(rustc -Vv | grep host | awk '{print $2}')
          USE_TARGET_FLAG=false
        else
          USE_TARGET_FLAG=true
        fi

        mkdir -p binaries

        # Create ALL placeholders first (Tauri build.rs requires all sidecar paths to exist)
        for BIN in worker net-scanner; do
          touch "binaries/${BIN}-${TARGET}"
          chmod +x "binaries/${BIN}-${TARGET}"
        done

        # Build all sidecar binaries
        if [ "$USE_TARGET_FLAG" = true ]; then
          if [ "$PROFILE" = "release" ]; then
            cargo build --bin worker --bin net-scanner --release --target "$TARGET"
          else
            cargo build --bin worker --bin net-scanner --target "$TARGET"
          fi
        else
          if [ "$PROFILE" = "release" ]; then
            cargo build --bin worker --bin net-scanner --release
          else
            cargo build --bin worker --bin net-scanner
          fi
        fi

        # Copy built binaries to sidecar path
        for BIN in worker net-scanner; do
          if [ "$USE_TARGET_FLAG" = true ]; then
            if [ "$PROFILE" = "release" ]; then
              cp "target/${TARGET}/release/${BIN}" "binaries/${BIN}-${TARGET}"
            else
              cp "target/${TARGET}/debug/${BIN}" "binaries/${BIN}-${TARGET}"
            fi
          else
            if [ "$PROFILE" = "release" ]; then
              cp "target/release/${BIN}" "binaries/${BIN}-${TARGET}"
            else
              cp "target/debug/${BIN}" "binaries/${BIN}-${TARGET}"
            fi
          fi
        done

    - name: Build sidecar (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: src-tauri
      run: |
        $Target = "${{ inputs.target }}"
        $Profile = "${{ inputs.profile }}"

        # Get host triple if target not specified
        if (-not $Target) {
          $Target = (rustc -Vv | Select-String "host:").Line.Split(":")[1].Trim()
          $UseTargetFlag = $false
        } else {
          $UseTargetFlag = $true
        }

        New-Item -ItemType Directory -Force -Path binaries | Out-Null

        # Create ALL placeholders first (Tauri build.rs requires all sidecar paths to exist)
        foreach ($Bin in @("worker", "net-scanner")) {
          New-Item -ItemType File -Force -Path "binaries/${Bin}-${Target}.exe" | Out-Null
        }

        # Build all sidecar binaries
        if ($UseTargetFlag) {
          if ($Profile -eq "release") {
            cargo build --bin worker --bin net-scanner --release --target $Target
          } else {
            cargo build --bin worker --bin net-scanner --target $Target
          }
        } else {
          if ($Profile -eq "release") {
            cargo build --bin worker --bin net-scanner --release
          } else {
            cargo build --bin worker --bin net-scanner
          }
        }

        # Copy built binaries to sidecar path
        foreach ($Bin in @("worker", "net-scanner")) {
          if ($UseTargetFlag) {
            if ($Profile -eq "release") {
              Copy-Item "target/${Target}/release/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            } else {
              Copy-Item "target/${Target}/debug/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            }
          } else {
            if ($Profile -eq "release") {
              Copy-Item "target/release/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            } else {
              Copy-Item "target/debug/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            }
          }
        }
