name: Build Sidecar Binaries
description: Build sidecar binaries for Tauri application

inputs:
  target:
    description: 'Rust target triple (e.g., x86_64-unknown-linux-gnu). If not specified, uses host triple.'
    required: false
    default: ''
  profile:
    description: 'Build profile (debug or release)'
    required: false
    default: 'debug'

runs:
  using: composite
  steps:
    - name: Build sidecar (Unix)
      if: runner.os != 'Windows'
      shell: bash
      working-directory: src-tauri
      run: |
        TARGET="${{ inputs.target }}"
        PROFILE="${{ inputs.profile }}"

        # Get host triple if target not specified
        if [ -z "$TARGET" ]; then
          TARGET=$(rustc -Vv | grep host | awk '{print $2}')
          USE_TARGET_FLAG=false
        else
          USE_TARGET_FLAG=true
        fi

        mkdir -p binaries

        # Build each sidecar binary
        for BIN in worker net-scanner; do
          # Create placeholder first (Tauri build.rs requires it)
          touch "binaries/${BIN}-${TARGET}"
          chmod +x "binaries/${BIN}-${TARGET}"

          # Build sidecar
          if [ "$USE_TARGET_FLAG" = true ]; then
            if [ "$PROFILE" = "release" ]; then
              cargo build --bin "$BIN" --release --target "$TARGET"
              cp "target/${TARGET}/release/${BIN}" "binaries/${BIN}-${TARGET}"
            else
              cargo build --bin "$BIN" --target "$TARGET"
              cp "target/${TARGET}/debug/${BIN}" "binaries/${BIN}-${TARGET}"
            fi
          else
            if [ "$PROFILE" = "release" ]; then
              cargo build --bin "$BIN" --release
              cp "target/release/${BIN}" "binaries/${BIN}-${TARGET}"
            else
              cargo build --bin "$BIN"
              cp "target/debug/${BIN}" "binaries/${BIN}-${TARGET}"
            fi
          fi
        done

    - name: Build sidecar (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      working-directory: src-tauri
      run: |
        $Target = "${{ inputs.target }}"
        $Profile = "${{ inputs.profile }}"

        # Get host triple if target not specified
        if (-not $Target) {
          $Target = (rustc -Vv | Select-String "host:").Line.Split(":")[1].Trim()
          $UseTargetFlag = $false
        } else {
          $UseTargetFlag = $true
        }

        New-Item -ItemType Directory -Force -Path binaries | Out-Null

        # Build each sidecar binary
        foreach ($Bin in @("worker", "net-scanner")) {
          # Create placeholder first (Tauri build.rs requires it)
          New-Item -ItemType File -Force -Path "binaries/${Bin}-${Target}.exe" | Out-Null

          # Build sidecar
          if ($UseTargetFlag) {
            if ($Profile -eq "release") {
              cargo build --bin $Bin --release --target $Target
              Copy-Item "target/${Target}/release/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            } else {
              cargo build --bin $Bin --target $Target
              Copy-Item "target/${Target}/debug/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            }
          } else {
            if ($Profile -eq "release") {
              cargo build --bin $Bin --release
              Copy-Item "target/release/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            } else {
              cargo build --bin $Bin
              Copy-Item "target/debug/${Bin}.exe" "binaries/${Bin}-${Target}.exe" -Force
            }
          }
        }
